# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BWStarry1604C' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    #     Pods for BWStarry1604C
    pod "AFNetworking"
    pod "SDWebImage"
    pod "MBProgressHUD"
    pod "MJRefresh"
    pod "MWPhotoBrowser"
    #  pod "WeiboSDK","3.1.3"
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCSecurityPlugins'
    pod "Weibo_SDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"
    pod 'mob_smssdk'
#    pod 'ZXingObjC', '3.2.1'
#    pod 'ZXingObjC',:git => "https://github.com/TheLevelUp/ZXingObjC.git" #'~> 3.2.1'
end
#clang: error: linker command failed with exit code 1 (use -v to see invocation)
