# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BWStarry1604C' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BWStarry1604C
  pod "AFNetworking"
  pod "SDWebImage"
  pod "MBProgressHUD"
  pod "MJRefresh"
  pod "MWPhotoBrowser"
#  pod ""

end
#clang: error: linker command failed with exit code 1 (use -v to see invocation)
